### ISSUE TITLE
AccountNotFound Error

### ISSUE THREAD

**Issue by wibuf** [precious-void/raydium-swap#1]
Just wondering if you came across this while developing this script

`Loaded pool keys
Found pool info
{
  context: { apiVersion: '1.17.20', slot: 247743888 },
  value: {
    accounts: null,
    err: 'AccountNotFound',
    logs: [],
    returnData: null,
    unitsConsumed: 0
  }
}`

Done a lot of searching but can't find a fix. Just using a free Helius account, not sure if that's the reason. 

Thanks

**Comment by precious-void** [comment]
I think that should have been fix with the latest PR on dynamic pool info selection #10
